[package]
name = "enum-tryfrom-derive"
version = "0.1.1"
authors = ["Kai Wohlfahrt <kai.scorpio@gmail.com>"]
description = "A crate to derive TryFrom<primitive> for enums"
license = "MIT"
repository = "https://github.com/kwohlfahrt/enum-tryfrom"

[dependencies]
syn = "0.11"
quote = "0.3"
clippy = {version = "0.0.136", optional = true}

[lib]
proc-macro = true

[features]
default = []

[dev-dependencies]
# For doc-tests
enum-tryfrom = { path = "..", version = "0.1" }
